archivage_index:
    path:     /
    defaults: { _controller: "BUBibliothequeBundle:Archivage:index" }
    methods:  GET

archivage_show:
    path:     /{id}/show
    defaults: { _controller: "BUBibliothequeBundle:Archivage:show" }
    methods:  GET

archivage_edit:
    path:     /{id}/edit
    defaults: { _controller: "BUBibliothequeBundle:Archivage:edit" }
    methods:  [GET, POST]

archivage_delete:
    path:     /{id}/delete
    defaults: { _controller: "BUBibliothequeBundle:Archivage:delete" }
    methods:  DELETE
    
archivage_new:
    path:     /new
    defaults: { _controller: "BUBibliothequeBundle:Archivage:new" }
    methods:  [GET, POST]
