emprunt_index:
    path:     /
    defaults: { _controller: "BUBibliothequeBundle:Emprunt:index" }
    methods:  GET

emprunt_show:
    path:     /{id}/show
    defaults: { _controller: "BUBibliothequeBundle:Emprunt:show" }
    methods:  GET

emprunt_new:
    path:     /new
    defaults: { _controller: "BUBibliothequeBundle:Emprunt:new" }
    methods:  [GET, POST]

emprunt_edit:
    path:     /{id}/edit
    defaults: { _controller: "BUBibliothequeBundle:Emprunt:edit" }
    methods:  [GET, POST]

emprunt_delete:
    path:     /{id}/delete
    defaults: { _controller: "BUBibliothequeBundle:Emprunt:delete" }
    methods:  DELETE
