etagere_index:
    path:     /
    defaults: { _controller: "BUBibliothequeBundle:Etagere:index" }
    methods:  GET

etagere_show:
    path:     /{id}/show
    defaults: { _controller: "BUBibliothequeBundle:Etagere:show" }
    methods:  GET

etagere_new:
    path:     /new
    defaults: { _controller: "BUBibliothequeBundle:Etagere:new" }
    methods:  [GET, POST]

etagere_edit:
    path:     /{id}/edit
    defaults: { _controller: "BUBibliothequeBundle:Etagere:edit" }
    methods:  [GET, POST]

etagere_delete:
    path:     /{id}/delete
    defaults: { _controller: "BUBibliothequeBundle:Etagere:delete" }
    methods:  DELETE

etagere_livre:
    path:     /livres/{id}
    defaults: { _controller: "BUBibliothequeBundle:Etagere:EtagLivre" }
    methods:  [GET, POST]