faculte_index:
    path:     /
    defaults: { _controller: "BUBibliothequeBundle:Faculte:index" }
    methods:  GET

faculte_show:
    path:     /{id}/show
    defaults: { _controller: "BUBibliothequeBundle:Faculte:show" }
    methods:  GET

faculte_new:
    path:     /new
    defaults: { _controller: "BUBibliothequeBundle:Faculte:new" }
    methods:  [GET, POST]

faculte_edit:
    path:     /{id}/edit
    defaults: { _controller: "BUBibliothequeBundle:Faculte:edit" }
    methods:  [GET, POST]

faculte_delete:
    path:     /{id}/delete
    defaults: { _controller: "BUBibliothequeBundle:Faculte:delete" }
    methods:  DELETE
