livre_index:
    path:     /
    defaults: { _controller: "BUBibliothequeBundle:Livre:index" }
    methods:  GET

livre_show:
    path:     /{id}/show
    defaults: { _controller: "BUBibliothequeBundle:Livre:show" }
    methods:  GET

livre_new:
    path:     /new
    defaults: { _controller: "BUBibliothequeBundle:Livre:new" }
    methods:  [GET, POST]

livre_edit:
    path:     /{id}/edit
    defaults: { _controller: "BUBibliothequeBundle:Livre:edit" }
    methods:  [GET, POST]

livre_delete:
    path:     /{id}/delete
    defaults: { _controller: "BUBibliothequeBundle:Livre:delete" }
    methods:  DELETE
    
user_Find_By_Auteur:
    path:     /SearchByAuteur  
    defaults: { _controller: "BUBibliothequeBundle:Livre:GetLivresByAuteur" }
    methods:  [GET, POST]
    
user_Find_By_Titre_Approximatif:
    path:     /SearchByTitreAppro  
    defaults: { _controller: "BUBibliothequeBundle:Livre:GetLivresByTitreApproximatif" }
    methods:  [GET, POST]

livre_Find_By_Theme:
    path:    /SearchByTheme
    defaults : { _controller: "BUBibliothequeBundle:Livre:GetLivresByTheme" }
    methods:  [GET, POST]