rayon_index:
    path:     /
    defaults: { _controller: "BUBibliothequeBundle:Rayon:index" }
    methods:  GET

rayon_show:
    path:     /{id}/show
    defaults: { _controller: "BUBibliothequeBundle:Rayon:show" }
    methods:  GET

rayon_new:
    path:     /new
    defaults: { _controller: "BUBibliothequeBundle:Rayon:new" }
    methods:  [GET, POST]

rayon_edit:
    path:     /{id}/edit
    defaults: { _controller: "BUBibliothequeBundle:Rayon:edit" }
    methods:  [GET, POST]

rayon_delete:
    path:     /{id}/delete
    defaults: { _controller: "BUBibliothequeBundle:Rayon:delete" }
    methods:  DELETE

rayon_livre:
    path:     /livres/{id}
    defaults: { _controller: "BUBibliothequeBundle:Rayon:RayonLivre" }
    methods:  [GET, POST]

rayon_etage:
    path:     /etages/{id}
    defaults: { _controller: "BUBibliothequeBundle:Rayon:RayonEtage" }