reservation_index:
    path:     /
    defaults: { _controller: "BUBibliothequeBundle:Reservation:index" }
    methods:  GET

reservation_show:
    path:     /{id}/show
    defaults: { _controller: "BUBibliothequeBundle:Reservation:show" }
    methods:  GET

reservation_new:
    path:     /new
    defaults: { _controller: "BUBibliothequeBundle:Reservation:new" }
    methods:  [GET, POST]

reservation_edit:
    path:     /{id}/edit
    defaults: { _controller: "BUBibliothequeBundle:Reservation:edit" }
    methods:  [GET, POST]

reservation_delete:
    path:     /{id}/delete
    defaults: { _controller: "BUBibliothequeBundle:Reservation:delete" }
    methods:  DELETE

reservation_Find_By_User:
    path:     /{id}/SearchByUser
    defaults: { _controller: "BUBibliothequeBundle:Reservation:SearchByUser" }
    methods:  GET