user_index:
    path:     /
    defaults: { _controller: "BUBibliothequeBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "BUBibliothequeBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "BUBibliothequeBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "BUBibliothequeBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BUBibliothequeBundle:User:delete" }
    methods:  DELETE

user_Find_By_Nom_Approximatif:
    path:     /SearchAppro  
    defaults: { _controller: "BUBibliothequeBundle:User:SearchAppro" }
    methods:  [GET, POST]
