<?php

namespace BU\BibliothequeBundle\Repository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * ArchivageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivageRepository extends \Doctrine\ORM\EntityRepository
{
}
