<?php

namespace BU\BibliothequeBundle\Repository;
use Doctrine\ORM\Query;
/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAuteur($nom, $prenom){
        $query = $this->getEntityManager()->createQuery("SELECT a FROM BUBibliothequeBundle:Auteur a 
                                                        WHERE a.nom = :nom AND a.prenom = :prenom ");
		$query->setParameter('nom', $nom);
        $query->setParameter('prenom', $prenom);
        return $query->getSingleResult();
    }
}
