<?php

namespace BU\BibliothequeBundle\Repository;
use Doctrine\ORM\Query;
/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAuteur($nom)
    {
        $query = $this->getEntityManager()->createQuery("SELECT a FROM BUBibliothequeBundle:Auteur a 
                                                        WHERE (a.nom like :nom) or (a.prenom like :prenom)");
		$query->setParameter('nom', '%'.$nom.'%');
        $query->setParameter('prenom', '%'.$nom.'%');
        return $query->getResult();
        
        /*$queryBuider = $this->createQueryBuilder('s');
		$queryBuider->where('s.nom LIKE :sousChaine')->setParameter('sousChaine', '%'.$chaine.'%');
        $queryBuider->orWhere('s.prenom LIKE :sousChaine')->setParameter('sousChaine', '%'.$chaine.'%');
        return $queryBuider->getQuery()->getResult();*/
        
       /* $queryBuider = $this->createQueryBuilder('a');
		$queryBuider->where('a.nom LIKE :sousChaine')->setParameter('sousChaine', '%'.$sousChaine.'%');
        $queryBuider->Orwhere('a.prenom LIKE :sousChaine')->setParameter('sousChaine', '%'.$sousChaine.'%');
		return $queryBuider->getQuery()->getResult();*/
        
         }
}
