<?php

namespace BU\BibliothequeBundle\Repository;
use Symfony\Component\Validator\Constraints\DateTime;
/**
 * EmpruntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpruntRepository extends \Doctrine\ORM\EntityRepository
{
    
   public function findEmpruntLivre($titre){
		$query = $this->getEntityManager()->createQuery("SELECT s FROM BUBibliothequeBundle:Emprunt s, BUBibliothequeBundle:Livre l, BUBibliothequeBundle:Exemplaire e 
                                                        WHERE l.titre = :title and l.id = e.livreexemplaire and e.id = s.livre ");
		$query->setParameter('title', $titre);
        return $query->getResult();
	}
    public function findEmpruntuser($Nom,$Prenom){
		$query = $this->getEntityManager()->createQuery("SELECT s FROM BUBibliothequeBundle:Emprunt s, BUBibliothequeBundle:User u 
                                                        WHERE u.nom= :nom and u.prenom = :prenom and u.id = s.user ");
		$query->setParameter('nom', $Nom);
        $query->setParameter('prenom', $Prenom);
        return $query->getResult();
	}
    public function findEmpuser($id){
		$query = $this->getEntityManager()->createQuery("SELECT COUNT(s) FROM BUBibliothequeBundle:Emprunt s
                                                        WHERE s.user = :id ");
		$query->setParameter('id', $id);
         return $query->getSingleScalarResult();
	}
    
    public function findEmphorsdelai(){
        $date = new \Datetime('now -15day');
		$query = $this->getEntityManager()->createQuery("SELECT s FROM BUBibliothequeBundle:Emprunt s, BUBibliothequeBundle:User u 
                                                        WHERE u.cycle = 1 and u.id = s.user and s.date < :date ");
		$query->setParameter('date', $date);
        return $query->getResult(); 
	}
     
}

