<?php

namespace BU\BibliothequeBundle\Repository;

/**
 * ExemplaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExemplaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findExemplaireLivre($titre){
		$query = $this->getEntityManager()->createQuery("SELECT COUNT(e) FROM  BUBibliothequeBundle:Livre l, BUBibliothequeBundle:Exemplaire e 
                                                        WHERE l.titre = :title and l.id = e.livreexemplaire");
		$query->setParameter('title', $titre);
       return $query->getSingleScalarResult();
	}
}
