<?php

namespace BU\BibliothequeBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findLivreByTitreApproximatif($sousChaine)
    {
        $queryBuider = $this->createQueryBuilder('s');
		$queryBuider->where('s.titre LIKE :sousChaine')->setParameter('sousChaine', '%'.$sousChaine.'%');
		return $queryBuider->getQuery()->getResult();
	}
    
    public function findLivreByTheme($ListeTheme)
    {
        $query = $this->getEntityManager()->createQuery("select l from BUBibliothequeBundle:Livre l, BUBibliothequeBundle:theme t, BUBibliothequeBundle:livre_theme lt
                                                         where lt.theme_id = t.id
                                                         and lt.livre_id = l.id
                                                         and t.id = (:ListeTheme) ");
        
        $query->setParameter('ListeTheme', array($ListeTheme));
        return $query->getResult();
    }
}
