<?php

namespace BU\BibliothequeBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findLivreByTitreApproximatif($sousChaine)
    {
        $queryBuider = $this->createQueryBuilder('s');
		$queryBuider->where('s.titre LIKE :sousChaine')->setParameter('sousChaine', '%'.$sousChaine.'%');
		return $queryBuider->getQuery()->getResult();
	}
}
