<?php

namespace BU\BibliothequeBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    public function findLivreByAuteur($auteur)
    {
		$query = $this->getEntityManager()->createQuery("select l.* from BUBibliothequeBundle:Livre l, BUBibliothequeBundle:Auteur a
                                                         where l.id = 
                                                         and  = a.id
                                                         and a.nom = :nom");

		$query->setParameter('nom', $nom);
        return $query->getResult();
	}
    
    public function findLivreByTitreApproximatif($sousChaine)
    {
        $queryBuider = $this->createQueryBuilder('s');
		$queryBuider->where('s.titre LIKE :sousChaine')->setParameter('sousChaine', '%'.$sousChaine.'%');
		return $queryBuider->getQuery()->getResult();
	}
}
