<?php

namespace BU\BibliothequeBundle\Repository;

/**
 * RayonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RayonRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findRayonLivre($idR){
		$query = $this->getEntityManager()->createQuery("SELECT e FROM  BUBibliothequeBundle:Livre l, BUBibliothequeBundle:Exemplaire e, BUBibliothequeBundle:Etagere et, BUBibliothequeBundle:Rayon r  
                                                        WHERE r.id = :idR and l.id = e.livreexemplaire and e.etagere = et.id and et.rayon = r.id");
        $query->setParameter('idR', $idR);
        return $query->getResult();
	}
}
