<?php

namespace BU\BibliothequeBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findReservationLivre($titre){
		$query = $this->getEntityManager()->createQuery("SELECT COUNT(r) FROM  BUBibliothequeBundle:Livre l, BUBibliothequeBundle:Reservation r
                                                        WHERE l.titre = :title and l.id = r.livre");
		$query->setParameter('title', $titre);
        return $query->getSingleScalarResult();
	}
}
