<?php

namespace BU\BibliothequeBundle\Repository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTheme($chaine){
        $query = $this->getEntityManager()->createQuery("SELECT t FROM BUBibliothequeBundle:Theme t 
                                                        WHERE t.id in (:id)");
		$query->setParameter('id', $chaine);
        return $query->getResult();
    }
}
