<?php

namespace BU\BibliothequeBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserByNomApproximatif($sousChaine)
    {
        $queryBuider = $this->createQueryBuilder('s');
		$queryBuider->where('s.nom LIKE :sousChaine')->setParameter('sousChaine', '%'.$sousChaine.'%');
		return $queryBuider->getQuery()->getResult();
	}
}
