<?php

namespace BU\BibliothequeBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserByNomApproximatif($sousChaine)
    {
        $queryBuider = $this->createQueryBuilder('s');
		$queryBuider->where('s.nom LIKE :sousChaine')->setParameter('sousChaine', '%'.$sousChaine.'%');
		return $queryBuider->getQuery()->getResult();
	}
    
    public function getListeEmpruntsByUserId($id)
    {
        $query = $this->getEntityManager()->createQuery("SELECT e FROM BUBibliothequeBundle:Emprunt e, BUBibliothequeBundle:User u, BUBibliothequeBundle:Livre l, BUBibliothequeBundle:Exemplaire Ex 
                                                         WHERE u.id = e.user 
                                                         AND l.id = Ex.livreexemplaire 
                                                         AND Ex.id = e.livre
                                                         AND e.user = :UserId");
                                                         
		$query->setParameter('UserId', $id);
        return $query->getResult();
	}
}
