BU\BibliothequeBundle\Entity\Auteur:
    type: entity
    table: null
    repositoryClass: BU\BibliothequeBundle\Repository\AuteurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        prenom:
            type: string
            length: 25
        nom:
            type: string
            length: 25
        titi:
            type : string
            length: 30
    manyToMany:
        livreauteur:
            targetEntity: Livre
            inversedBy: auteurs
    lifecycleCallbacks: {  }
