BU\BibliothequeBundle\Entity\Emprunt:
    type: entity
    repositoryClass: BU\BibliothequeBundle\Repository\EmpruntRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
       livre:
            targetEntity: Exemplaire
            inversedBy: livreemprunt
            cascade: [ persist ]
            joinColumn:
               onDelete: cascade        
    manyToOne:    
        user:
            targetEntity: User
            inversedBy: empruntuser
            cascade: [ persist ]
            joinColumn:
                onDelete: cascade
    fields:
        date:
           type: date
    lifecycleCallbacks: {  }
            

