BU\BibliothequeBundle\Entity\Etagere:
    type: entity
    table: null
    repositoryClass: BU\BibliothequeBundle\Repository\EtagereRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        numero:
            type: smallint
    manyToOne:
        rayon:
           targetEntity: Rayon
           inversedBy: rayons
           cascade: [ persist ]
           joinColumn:
              onDelete: cascade
    oneToMany:
        livres:
           targetEntity: Livre
           mappedBy: etagere
    lifecycleCallbacks: {  }
