BU\BibliothequeBundle\Entity\Livre:
    type: entity
    table: null
    repositoryClass: BU\BibliothequeBundle\Repository\LivreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 50
        notice:
            type: string
            length: 255
    manyToMany:
        themes:
            targetEntity: Theme
            inversedBy: livretheme
    manyToMany:
        auteurs:
            targetEntity: Auteur
            inversedBy: livreauteur
    manyToOne:
        etagere:
           targetEntity: Etagere
           inversedBy: livres
           cascade: [ persist ]
           joinColumn:
              onDelete: cascade
    oneToMany:
        livreemprunt:
            targetEntity: Emprunt
            mappedBy: livre
    lifecycleCallbacks: {  }
