BU\BibliothequeBundle\Entity\Livre:
    type: entity
    table: null
    repositoryClass: BU\BibliothequeBundle\Repository\LivreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 50
        notice:
            type: string
            length: 255
    manyToMany:
        themes:
            targetEntity: Theme
            inversedBy: livretheme
        auteurs:
            targetEntity: Auteur
            mappedBy: livreauteur
    oneToMany:
        exemplaires:
            targetEntity: Exemplaire
            mappedBy: livreexemplaire
        livrereservation:
            targetEntity: Reservation
            mappedBy: livre
        livreemprunt:
            targetEntity: Emprunt
            mappedBy:  livre
        livreempruntarch:
            targetEntity: Archivage
            mappedBy:  livre
    lifecycleCallbacks: {  }
