BU\BibliothequeBundle\Entity\Reservation:
    type: entity
    repositoryClass: BU\BibliothequeBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        livre:
            targetEntity: Livre
            inversedBy: livrereservation
            cascade: [ persist ]
            joinColumn:
               onDelete: cascade
        user:
            targetEntity: User
            inversedBy: userreservation
            cascade: [ persist ]
            joinColumn:
                onDelete: cascade
    fields:
        date:
           type: date
    lifecycleCallbacks: {  }
            

